name: Examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  bazel:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Bazel Test
      run: cd examples/bazel && bazel test --cxxopt=-std=c++23 --host_cxxopt=-std=c++23 //...
